import sqlite3
conn = sqlite3.connect('pharmacy.db')
c = conn.cursor()
c.execute()
c.execute()
c.execute()
c.execute()
c.execute("DELETE FROM sale_items")
c.execute("DELETE FROM sales")
c.execute("DELETE FROM medicines")
c.execute("DELETE FROM users")
c.execute("INSERT INTO users (username, password, role) VALUES ('admin@gmail.com', 'admin123', 'admin')")
c.execute("INSERT INTO users (username, password, role) VALUES ('jeevan@gmail.com', 'jeevan', 'user')")
c.execute("INSERT INTO medicines (name, category, manufacturer, price, expiry_date, stock) VALUES ('Paracetamol', 'Tablet', 'Cipla', 10.50, '2027-01-01', 200)")
c.execute("INSERT INTO medicines (name, category, manufacturer, price, expiry_date, stock) VALUES ('Amoxicillin', 'Capsule', 'Sun Pharma', 20.00, '2026-06-01', 100)")
c.execute("INSERT INTO medicines (name, category, manufacturer, price, expiry_date, stock) VALUES ('Cough Syrup', 'Liquid', 'Dabur', 50.00, '2026-12-01', 50)")
conn.commit()
conn.close()
print("Database initialized successfully.")